# -*- coding: utf-8 -*-
"""Handson In oil and gas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4apnKVoUNlUk_Ni0N7CLaPZ_jfMIr2Q

Problem Statement: We have various types of the lithologies on the basis of their matrix densities. But in most of the cases of the cases there are mainly 6 types of formation: sandstone,limestone,dolomite,clay,anhydrite,shale. Write a programme that takes input the mineral composition of the lithologies from the user and display the matrix densities accordingly.

Concept used: We know that different lithologies have different grain composition and matrix density.The matrix density range can overlapp for more than one lithology but the grain compositiob is unique which is listed below.
Formation   Mineral Main Composition    Density range(gm/cc)

sandstone   lithified quartz grains     1.9-2.65
limestone   chiefly calcite             2.2-2.71
dolomite    chiefly Dolomite            2.3-2.87 
clay        chiefly clay minerals       1.1-1.8
anhydrite   Mainly Calcium Sulphate     2.98
shale       Mainly Quartz               2.4-2.8
"""

matrix_composition=  input("Enter the matrix composition of the formation")
matrix_densitiy= float(input("Enter the matrix density of the formation in gm/cc ?")) 
if(matrix_composition =="lithified quartz grains"):    # Error what i was doing is matrix_composition ="lithified quartz grains" but it should be matrix_composition =="lithified quartz grains"
  if(1.9<=matrix_densitiy<=2.65):
    print("Lithology is of Sandstone Formation")
elif (matrix_composition=="chiefly calcite"):  
  if(2.2<=matrix_densitiy<=2.71):
    print("Lithology is of Limestone Formation")       # Identation error that is coming when print and if get align along the same axis.
elif (matrix_composition=="Dolomite"):  
  if(2.3<=matrix_densitiy<=2.871):
    print("Lithology is of Dolomite Formation")
elif (matrix_composition=="clay minerals"):  
  if(1.1 <=matrix_densitiy <=1.8):   
    print("Lithology is of Clay Formation")
elif (matrix_composition=="Calcium Sulphate"):  
  if(matrix_densitiy==2.98):
    print("Lithology is of Anhydrite Formation")
elif (matrix_composition=="Quartz"):  
  if(2.4<=matrix_densitiy<=2.8):
    print("Lithology is of Shale Formation")
#elif:
    #print("No litholgy exists")

